# Generated by Django 4.2.3 on 2023-09-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(through="blog.PostCategory", to="blog.category", verbose_name="categories"),
        ),
    ]
