version: '3'

services:
  db:
    container_name: "project_db"
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=project_db

  redis:
    container_name: "project_redis"
    image: "redis:6.2.6-alpine"
    ports:
      - '6379:6379'
