# Generated by Django 4.2.3 on 2023-10-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_confirmed",
            field=models.BooleanField(default=False, verbose_name="is email confirmed?"),
        ),
    ]
